### ISSUE TITLE
category_nameがcategory_tableに登録しようとするとUnpermitted parametersと言われてしまう。

### ISSUE THREAD

**Issue by naota7118** [naota7118/idea-api#3]
category_nameがcategory_tableに登録できません。
調査しましょう。

**Comment by naota7118** [comment]
`curl --data '{"body":"zzz", "category_id":2, "name": "zzz"}' -H "Content-Type: application/json" -X POST http://localhost:3000/ideas`

これでアイディア名、カテゴリーid、カテゴリー名を登録しようとしたところ、`Unpermitted parameters: :body, :category_id, :idea`と表示されました。

**Comment by naota7118** [comment]
問題を整理しましょう。今は何をしようとしていますか？

**Comment by naota7118** [comment]
curlコマンドでアイディア名、カテゴリーidをideasテーブルに、カテゴリー名をcategoriesテーブルに登録しようとしています。

**Comment by naota7118** [comment]
どのような問題が生じていますか？  
その原因は何だと推測しますか？

**Comment by naota7118** [comment]
アイディア名、カテゴリーidをideasテーブルに、カテゴリー名をcategoriesテーブルに登録することは一応できているのですが、「Unpermitted parameters: :body, :category_id, :idea (ideasテーブルのbodyカラムとcategory_idカラムのパラメーターが許可されていない)」と言われる問題が発生しています。
原因はストロングパラメーターの設定にあると推測しています。
現状、itemsコントローラーは下記のように設定してあります。

```ruby:ideas_controller.rb
def create
  @idea = Idea.new(idea_params)
  @category = Category.new(category_params)

  if @idea.save && @category.save      
    # ステータスコード201を返す
    head :created, location: idea_path(@idea)
  else

    # ステータスコード422を返す（バリデーションエラー時）
    head :unprocessable_entity
  end
end

private
  def idea_params
    params.require(:idea).permit(:body, :category_id)
  end

  def category_params
    params.permit(:name)
  end
```

**Comment by naota7118** [comment]
リクエストとレスポンスを見せてもらえますか？

**Comment by naota7118** [comment]
# リクエスト

```
curl --data '{"body":"zzz", "category_id":2, "name": "zzz"}' -H "Content-Type: application/json" -X POST http://localhost:3000/ideas
```

# レスポンス
```
Started POST "/ideas" for ::1 at 2020-11-19 15:31:06 +0900
   (6.0ms)  SET NAMES utf8mb4,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
Processing by IdeasController#create as */*
  Parameters: {"body"=>"zzz", "category_id"=>2, "name"=>"zzz", "idea"=>{"body"=>"zzz", "category_id"=>2}}
Unpermitted parameters: :body, :category_id, :idea
   (2.1ms)  BEGIN
  ↳ app/controllers/ideas_controller.rb:17:in `create'
  Category Load (2.8ms)  SELECT `categories`.* FROM `categories` WHERE `categories`.`id` = 2 LIMIT 1
  ↳ app/controllers/ideas_controller.rb:17:in `create'
  Idea Create (2.6ms)  INSERT INTO `ideas` (`body`, `created_at`, `updated_at`, `category_id`) VALUES ('zzz', '2020-11-19 06:31:06.918133', '2020-11-19 06:31:06.918133', 2)
  ↳ app/controllers/ideas_controller.rb:17:in `create'
   (2.5ms)  COMMIT
  ↳ app/controllers/ideas_controller.rb:17:in `create'
   (0.3ms)  BEGIN
  ↳ app/controllers/ideas_controller.rb:17:in `create'
  Category Create (4.3ms)  INSERT INTO `categories` (`name`, `created_at`, `updated_at`) VALUES ('zzz', '2020-11-19 06:31:06.983087', '2020-11-19 06:31:06.983087')
  ↳ app/controllers/ideas_controller.rb:17:in `create'
   (0.6ms)  COMMIT
  ↳ app/controllers/ideas_controller.rb:17:in `create'
Completed 201 Created in 166ms (ActiveRecord: 15.2ms | Allocations: 6252)
```

**Comment by naota7118** [comment]
まだ問題が全て解決したわけではないのですが、わかったことがあるので、共有させていただきます。

# わかったこと
`$ curl --data '{"モデル名1":{"カラム名1":"登録するデータ1"},"モデル名2":{"カラム名2":"登録するデータ2"}}' -H "Content-Type: application/json" -X POST http://localhost:3000/ideas`
このように書くことで、1回のcurlコマンドで2つのモデルにデータを登録することができます。

今回はこのように書くことで、ideasテーブルとcategoriesテーブルの2つのテーブルにそれぞれデータを登録することができました。
```
curl --data '{"idea":{"body":"todoリストをつくる"},"category":{"name":"仕事"}}' -H "Content-Type: application/json" -X POST http://localhost:3000/ideas
```
